### PR TITLE
Add ttCore dependency

### PR DESCRIPTION
**Pull request by tterrag1098**
OpenEye crashes are pinging me -.-

### CODE REVIEW

**Comment by tterrag1098** [comment]
WRONG BRANCH ARGH

**Comment by tterrag1098** [comment]
It's still crashing though...so idk

**Comment by tterrag1098** [comment]
nvm http://openeye.openmods.info/crashes/e0f507118fec781b064c0a10aabafd8e

They were running build 1.

1.

What.

**Comment by TehNut** [comment]
But... Why... w0t

**Pull request closed without merging**
